Package Info Api
Nasz-Elektryk/spito-rules pull request #12
Opened 2023-10-16 14:15 UTC by BaderBC

Closes #5
Implements docker for testing

- package info API done
- docker config for tests
- package test added

2023-10-16 18:25 UTC, sewe2000 commented on src/api/package.go
I think the function 'getPackageInfo' should be renamed to 'GetPackageInfo' in order to export this function (so it could be used in other go files such as main.go). I wonder if the 'SetField' method is really needed (do you want to implement some kind of validation?). There's also a big problem regarding the 'Get' method because I presume it only works with the English locale. For example if a user has polish locale, then this function won't work because there's no field 'Licencje' in struct 'Package'. We need to discuss this issue more thoroughly. Overall the code is good

2023-10-16 20:09 UTC, cooligus reviewed
IMO test is currently like a small boy shouting at you "add me to your class group!"

2023-10-16 20:43 UTC, BaderBC commented
> IMO test is currently like a small boy shouting at you "add me to your class group!"

I think that we should use test driven architecture or at least something similar.
This project, especially API part is just library, so it is hard to develop code without any tests.

2023-10-16 20:56 UTC, BaderBC commented on src/api/package.go
getPackageInfo is private on purpose, because it returns package info as (string, error). I don't think string containing output of "pacman -Qi package" command will be useful in any other file.

setField is method which I created to avoid putting all logic into one long function. Maybe I'm wrong, but I think it makes code cleaner and more readable. (body of setField could be not really meaningful so I separate this into function called setField which explains what that block of code does)

Speaking about the biggest problem that you fortunately found, I find out how to resolve. Here's how: "LANG=C pacman -Qi package". I will fix this one in next commit.

2023-10-17 06:54 UTC, cooligus reviewed
So are you going to create test in this pull request or maybe in another?

2023-10-17 19:59 UTC, BaderBC commented
Just added GitHub actions CI for testing

2023-10-17 20:06 UTC, maxidragon requested changes

2023-10-17 20:06 UTC, maxidragon commented on .github/workflows/test.yml
> +name: docker_test
Please change name to Test

2023-10-17 20:26 UTC, maxidragon approved these changes
LGTM, but please wait for someone else to approve before merging

2023-10-18 08:27 UTC, cooligus approved these changes

2023-10-18 12:34 UTC, sewe2000 approved these changes

2023-10-18 12:37 UTC, BaderBC commented on src/api/package.go
setField make code cleaner, because it contain additional logic beyond just assigning value to key

2023-10-18 12:39 UTC, merged