lua integration
Nasz-Elektryk/spito-rules pull request #18
Opened 2023-10-23 19:21 UTC by BaderBC

- lua integrated
- api.Package fixed

2023-10-23 19:26 UTC, maxidragon commented on src/lua/api_binding.go
> +// Every api needs to be attached here in oder to be available:
there is a typo 😉
```suggestion
// Every api needs to be attached here in order to be available:
```

2023-10-23 19:36 UTC, cooligus requested changes
Don't forget to add GetDaemon

2023-10-23 19:36 UTC, cooligus commented on src/lua/interpreter.go
> +		panic(err)
```go
return false, err
```

2023-10-24 09:25 UTC, cooligus approved these changes

2023-10-24 09:25 UTC, maxidragon approved these changes
Please wait for @cooligus approval before merging

2023-10-24 09:27 UTC, merged